### ISSUE TITLE
SyntaxError : invalid syntax

### ISSUE THREAD

**Issue by playground7** [seemoo-lab/internalblue#29]
Hi, 

I have tried to run the command with python(python2).

~/internalblue$ sudo python -m internalblue.cli

I got the following error.

<img width="1013" alt="스크린샷 2020-07-06 오후 12 15 38" src="https://user-images.githubusercontent.com/67093841/86554726-625e6680-bf89-11ea-8c57-df1952b5c850.png">

Could you please let me know what is the solution for this issue?

**Comment by fmagin** [comment]
The current `internalblue` version does not support Python 2 anymore, which reached its end of life on 2020.01.01. 

If you have a specific reason that leaves you no other option but to run it with Python 2, you can use the [python2 tag](https://github.com/seemoo-lab/internalblue/tree/python2) for now, which is the latest internalblue version still supporting Python 2. Otherwise, installing it the instructions in the [setup.md](https://github.com/seemoo-lab/internalblue/blob/master/doc/setup.md#install-as-package-from-github-master-or-any-other-branch) should work. Note that if you are on a LTS release of ubuntu, `pip` might still be the python2 version, and the `pip` commands need to be replaced with `pip3`
