### ISSUE TITLE
commands require root

### ISSUE THREAD

**Issue by lometsj** [seemoo-lab/internalblue#39]
im using raspberry 4.even though i run internalbule with root user,it shows
```
_sendThreadFunc: Sending to socket failed, reestablishing connection.
    With HCI sockets, some HCI commands require root!
```
what shall i do to figure it.

**Comment by jiska2342** [comment]
Hi @lometsj,

some HCI commands require `root` on Linux, meaning that they time out if they're not sent as `root`.

In your case, when you're already executing *InternalBlue* as `root`, the reason is more likely that your HCI interface is down or the *BlueZ* stack is not running properly. Can you actually scan for nearby devices, establish connections, etc. using `hcitool` or `bluetoothctl`?
