### ISSUE TITLE
Flashing original HCI firmware back to Cypress eval board.

### ISSUE THREAD

**Issue by vaibhvbedi** [seemoo-lab/internalblue#51]
I've flashed a different sample code on CYW920735Q60EVB-01, how can I go back to the original HCI firmware so I can use internalblue again

**Comment by jiska2342** [comment]
It should be possible to use InternalBlue with all samples. Using Cypress WICED Studio you can always flash the original Hello Sensor application. You should also be able to reset the firmware by pressing the buttons on the board as follows:

* Press Recover and keep it pressed
* Additionally press Reset
* Release Reset
* Release Recover

I think that was the button combo but maybe also the other way round (Recover/Reset switched). That being said, it really shouldn't matter which firmware is on your evaluation board, since this is all stuff in the Patchram and the ROM keeps unchanged.
